//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T03.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticaS13Entities : DbContext
    {
        public PracticaS13Entities()
            : base("name=PracticaS13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonos> Abonos { get; set; }
        public virtual DbSet<Principal> Principal { get; set; }
    
        public virtual ObjectResult<sp_ConsultarCompras_Result> sp_ConsultarCompras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarCompras_Result>("sp_ConsultarCompras");
        }
    
        public virtual ObjectResult<sp_ConsultarComprasPendientes_Result> sp_ConsultarComprasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarComprasPendientes_Result>("sp_ConsultarComprasPendientes");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_ConsultarSaldo(Nullable<long> vId_Compra)
        {
            var vId_CompraParameter = vId_Compra.HasValue ?
                new ObjectParameter("vId_Compra", vId_Compra) :
                new ObjectParameter("vId_Compra", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_ConsultarSaldo", vId_CompraParameter);
        }
    
        public virtual int sp_PagoParcial(Nullable<long> vId_Compra, Nullable<decimal> vMonto)
        {
            var vId_CompraParameter = vId_Compra.HasValue ?
                new ObjectParameter("vId_Compra", vId_Compra) :
                new ObjectParameter("vId_Compra", typeof(long));
    
            var vMontoParameter = vMonto.HasValue ?
                new ObjectParameter("vMonto", vMonto) :
                new ObjectParameter("vMonto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PagoParcial", vId_CompraParameter, vMontoParameter);
        }
    }
}
